accounts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = "accounts"

urlpatterns = [
    path('', views.demo, name='demo'),
    path('login/', views.login_page, name='login_page'),

    path('user_signup/', views.user_signup, name='user_signup'),
    path('admin_signup/', views.admin_signup, name='admin_signup'),
    path('owner_signup/', views.owner_signup, name='owner_signup'),

    path('logout_user/', views.logout_user, name='logout_user'),




] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

vehicalrental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('admin_panel/', include('admin_panel.urls')),
    path('owner_panel/', include('owner_panel.urls')),
    path('user_panel/', include('user_panel.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from re import T
from django.db import models
from django.contrib.auth.models import AbstractUser
from .managers import CustomUserManager
from django.core.validators import RegexValidator
from django.utils.translation import gettext_lazy as _


Status = (
    ('ahmedabad', 'ahmedabad'),
    ('Rajkot','Rajkot'),
    ('Delhi','Delhi'),
    ('Mumbai','Mumbai'),
    ('hyderabad','hyderabad'),
    ('Goa','Goa'),
    ('vadodara','vadodara'),
)

class User(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    Mobile_Number = models.CharField(max_length=10, validators=[
                                     RegexValidator(r'^\d{10}$')])
    Rest_Name = models.CharField(max_length=80, null=True, blank=True)
    Address = models.CharField(max_length=200)
    State = models.CharField(max_length=20, choices=Status)
    Pincode = models.CharField(max_length=6, validators=[
        RegexValidator(r'^\d{6}$')])
    is_user = models.BooleanField(default=False)
    is_super = models.BooleanField(default=False)
    is_owner = models.BooleanField(default=False)
    status = models.BooleanField(default=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.first_name + ' ' + self.last_name

accounts/forms.py
from dataclasses import field
from django import forms
from .models import User

class UserloginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'Mobile_Number', 'Pincode')
       

class ownerloginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'password', 'State')
        widgets = {
            'email': forms.EmailInput(attrs={
                'class':'mb-3 form-control',
            }),
            'password': forms.PasswordInput(attrs={
                'class':'mb-3 form-control',
            }),
            'State': forms.Select(attrs={
                
            }),

        }

class adminloginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'password',)

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout


from django.contrib import messages
from .models import *
from django.urls import reverse
from .forms import *


# Create your views here.

def demo(request):
    return redirect("accounts:login_page")


def user_signup(request):
    if request.method == "POST":
        form_v = UserloginForm(request.POST, request.FILES)
        if form_v.is_valid():
            asd = form_v.save()
            asd.is_user = True
            asd.set_password(asd.password)
            asd.save()
            return redirect("accounts:login_page")
        else:
            print(form_v.errors)
    else: 
        form_v = UserloginForm()
    return render (request, "accounts/user_signup.html", {'form': form_v})
        

def admin_signup(request):
    if request.method == "POST":
        form_v = adminloginForm(request.POST, request.FILES)
        if form_v.is_valid():
            asd = form_v.save()
            asd.is_super = True
            asd.set_password(asd.password)
            asd.save()
            return redirect("accounts:login_page")
        else:
            print(form_v.errors)
    else: 
        form_v = adminloginForm()
    return render (request, "accounts/admin_signup.html", {'form': form_v})

    
def owner_signup(request):
    if request.method == "POST":
        form_v = ownerloginForm(request.POST, request.FILES)
        if form_v.is_valid():
            asd = form_v.save()
            asd.is_owner = True
            asd.set_password(asd.password)
            asd.save()
            return redirect("accounts:login_page")
        else:
            print(form_v.errors)
    else: 
        form_v = ownerloginForm()
    return render (request, "accounts/owner_signup.html", {'form': form_v})

        
def login_page(request):        
    if request.method == 'POST':
        username = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active and user.is_super:
                login(request, user)
                return HttpResponseRedirect(reverse('admin_panel:home'))
            if user.is_active and user.is_user:
                login(request, user)
                return HttpResponseRedirect(reverse('user_panel:home'))
            if user.is_active and user.is_owner:
                login(request, user)
                return HttpResponseRedirect(reverse('owner_panel:home'))
            else:                
                messages.warning(request, 'User is Not Active')
                return HttpResponseRedirect(reverse('accounts:user_login'))
        else:
            print("error")
            messages.warning(request, 'Username or Password is Wrong')
            return HttpResponseRedirect(reverse('accounts:user_login'))
    else:
        return render(request, 'accounts/login.html', {})


def logout_user(request):
    logout(request)
    return redirect("accounts:login_page")

templates/accounts/admin_signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css\style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" charset="utf-8"></script>
    <title>Admin SignUp</title>

    <style>
        body{
            background-image: linear-gradient(120deg,#8e44ad,#3498db);
            

        }
    </style>

</head>
<body>
    <!-- <form method="POST">
    User Add
    {% csrf_token %}
        {{ form. }}
    <input type="submit">
</form> -->

<form method="POST" class="login-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form. }}
    <h1>Admin Sign Up</h1>
    
    <div class="txtb">
        <input type="email" name="email">
        <span data-placeholder="email" ></span>
    </div>

    <div class="txtb">
        <input type="password" name="password">
        <span data-placeholder="Password" ></span>
    </div>

    <!-- <input type="file" id="img" name="image" accept="image/*" id="id_image">
    <br><br>     -->

    <!-- <div class="txtb">
        <input type="file" name="image" accept="image/*">
        <span data-placeholder="image" ></span>

    </div> -->

    <input type="submit" class="logbtn" value="Sigh Up">
    <br>
    <div class="bottom-text">
        <a href="{% url 'accounts:login_page' %}"><b>Login</b></a>
    </div>
    
    
    


</form>
<script type="text/javascript">
    $(".txtb input").on("focus",function(){
        $(this).addClass("focus");
    })

    $(".txtb input").on("blur",function(){
        if($(this).val() == "")
        $(this).removeClass("focus");
    })

</script>

</body>
</html>

templates/accounts/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
        <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}"> -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <!-- <link rel="icon" type="image/x-icon" href="{% static 'images/blood.png' %}"> -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" charset="utf-8"></script>

        <style>
            .bottom-text{
                margin-top: 20px !important;
            }
        </style>

    </head>
    <body>

        <form method="POST" class="login-form">
            {% csrf_token %}
            <h1>Login</h1>
            
            <div class="txtb">
                <input type="email" name="email">
                <span data-placeholder="email" ></span>
            </div>

            <div class="txtb">
                <input type="password" name="password">
                <span data-placeholder="Password" ></span>
            </div>

            <input type="submit" class="logbtn" value="Login">            
            <div class="bottom-text">
                Don`t have account? <a href="{% url 'accounts:user_signup' %}"><b>User Sign up</b></a>
            </div>

            <div class="bottom-text">
                Don`t have account? <a href="{% url 'accounts:admin_signup' %}"><b>Admin Sign up</b></a>
            </div>

            <div class="bottom-text">
                Don`t have account? <a href="{% url 'accounts:owner_signup' %}"><b>Owner Sign up</b></a>
            </div>

        </form>
        <script type="text/javascript">
            $(".txtb input").on("focus",function(){
                $(this).addClass("focus");
            })

            $(".txtb input").on("blur",function(){
                if($(this).val() == "")
                $(this).removeClass("focus");
            })
        </script>

      
            
        

    </body>
</html>

templates/accounts/owner_signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css\style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" charset="utf-8"></script>
    <title>Owner SignUp</title>

    <style>
        body{
            background-image: linear-gradient(120deg,#8e44ad,#3498db);
            

        }
    </style>

</head>
<body>
    <!-- <form method="POST">
    User Add
    {% csrf_token %}
        {{ form. }}
    <input type="submit">
</form> -->

<form method="POST" class="login-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form. }}
    <h1>Owner Sign Up</h1>
    
    <div class="txtb">
        {{ form.email}}
        <span data-placeholder="email" ></span>
    </div>

    <div class="txtb">
        {{ form.password}}
        <span data-placeholder="Password" ></span>
    </div>
    
    <div class="txtb">
        {{ form.State}}
        <span data-placeholder="Password" ></span>
    </div>

    <!-- <input type="file" id="img" name="image" accept="image/*" id="id_image">
    <br><br>     -->

    <!-- <div class="txtb">
        <input type="file" name="image" accept="image/*">
        <span data-placeholder="image" ></span>

    </div> -->

    <input type="submit" class="logbtn" value="Sigh Up">
    <br>
    <div class="bottom-text">
        <a href="{% url 'accounts:login_page' %}"><b>Login</b></a>
    </div>
    
    
    


</form>
<script type="text/javascript">
    $(".txtb input").on("focus",function(){
        $(this).addClass("focus");
    })

    $(".txtb input").on("blur",function(){
        if($(this).val() == "")
        $(this).removeClass("focus");
    })

</script>

</body>
</html>

templates/accounts/user_signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css\style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" charset="utf-8"></script>
    <title>User SignUp</title>

    <style>
        body{
            background-image: linear-gradient(120deg,#8e44ad,#3498db);
        }
        .login-form{
            height: 700px !important;
            padding: 60px 40px !important;
        }    
    </style>

</head>
<body>
    <!-- <form method="POST">
    User Add
    {% csrf_token %}
        {{ form. }}
    <input type="submit">
</form> -->

<form method="POST" class="login-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form. }}
    <h1>User Sign Up</h1>
    
    <div class="txtb">
        <input type="text" name="first_name">
        <span data-placeholder="first_name" ></span>
    </div>
    
    <div class="txtb">
        <input type="text" name="last_name">
        <span data-placeholder="last_name" ></span>
    </div>

    <div class="txtb">
        <input type="email" name="email">
        <span data-placeholder="email" ></span>
    </div>

    <div class="txtb">
        <input type="password" name="password">
        <span data-placeholder="Password" ></span>
    </div>
    
    <div class="txtb">
        <input type="number" name="Mobile_Number">
        <span data-placeholder="Mobile_Number" ></span>
    </div>
    
    <div class="txtb">
        <input type="number" name="Pincode">
        <span data-placeholder="Pincode" ></span>
    </div>


    <!-- <input type="file" id="img" name="image" accept="image/*" id="id_image">
    <br><br>     -->

    <!-- <div class="txtb">
        <input type="file" name="image" accept="image/*">
        <span data-placeholder="image" ></span>

    </div> -->

    <input type="submit" class="logbtn" value="Sigh Up">
    <br>
    <div >
        <a href="{% url 'accounts:login_page' %}"><b>Login</b></a>
    </div>
    
    
    


</form>
<script type="text/javascript">
    $(".txtb input").on("focus",function(){
        $(this).addClass("focus");
    })

    $(".txtb input").on("blur",function(){
        if($(this).val() == "")
        $(this).removeClass("focus");
    })

</script>

</body>
</html>