accounts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = "accounts"

urlpatterns = [
    path('', views.demo, name='demo'),
    path('login/', views.login_page, name='login_page'),

    path('user_signup/', views.user_signup, name='user_signup'),
    path('admin_signup/', views.admin_signup, name='admin_signup'),
    path('owner_signup/', views.owner_signup, name='owner_signup'),

    path('logout_user/', views.logout_user, name='logout_user'),




] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

owner_panel/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = "owner_panel"

urlpatterns = [
    
    path('home/', views.home, name='home'),

    path('Rent_Vehical/', views.Rent_Vehical, name='Rent_Vehical'),
    
    path('ownervehicledetails/', views.ownervehicledetails, name='ownervehicledetails'),
    path('delete_vehicle/<int:id>', views.delete_vehicle, name='delete_vehicle'),




   
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

vehicalrental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('admin_panel/', include('admin_panel.urls')),
    path('owner_panel/', include('owner_panel.urls')),
    path('user_panel/', include('user_panel.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

owner_panel/models.py
from django.db import models

# Create your models here.

owner_panel/forms.py
from dataclasses import field
from tkinter import Widget
from admin_panel.models import Vehical_Registration
from django import forms



class Vehical_Registration_owner_form(forms.ModelForm):
    class Meta:
        model  = Vehical_Registration
        fields = '__all__'
        exclude = ('AddDate','UserId', 'Status')

class owner_VehicleDetails_form(forms.ModelForm):
    class Meta:
        model  = Vehical_Registration
        fields = '__all__'
        exclude = ('AddDate','UserId',)

owner_panel/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib import messages
from admin_panel.models import *
from django.urls import reverse
from owner_panel.forms import *

# from django.contrib.auth import authenticate, login, logout


def home(request):
    return render(request, "owner_panel/home.html")


def Rent_Vehical(request):
    if request.method == 'POST':
        form = Vehical_Registration_owner_form(request.POST, request.FILES)
        if form.is_valid():
            data = form.save(commit=False)
            data.UserId=request.user
            data.save()
            return HttpResponseRedirect(reverse('owner_panel:Rent_Vehical'))
        else:
            print(form.errors)
    else:
        form = Vehical_Registration_owner_form()
        data = Vehical_Registration.objects.all()
    return render(request, 'owner_panel/Rent_Vehical.html', {'form': form, 'data' : data})





def ownervehicledetails(request):
    form = owner_VehicleDetails_form()
    
    data = Vehical_Registration.objects.filter(UserId=request.user.id)
    # data = Vehical_Registration.objects.filter(UserId=request.user.id, Status="Available")
    return render(request, 'owner_panel/Vehical_Details.html', {'data' : data, 'form': form})


def delete_vehicle(request, id):
    details = Vehical_Registration.objects.get(id=id)
    details.delete()
    return redirect("owner_panel:ownervehicledetails")

templates/owner_panel/Rent_Vehical.html
{% extends 'owner_panel/base.html' %}
{% load static %}

{% block main %}

<!-- Banner Starts Here -->

<div class="banner header-text">
    <div class="owl-banner owl-carousel">
      <div class="banner-item-01">
        <div class="text-content">
          <h4>Find your car today!</h4>
          <h2>Lorem ipsum dolor sit amet</h2>
        </div>
      </div>
      <div class="banner-item-02">
        <div class="text-content">
          <h4>Fugiat Aspernatur</h4>
          <h2>Laboriosam reprehenderit ducimus</h2>
        </div>
      </div>
      <div class="banner-item-03">
        <div class="text-content">
          <h4>Saepe Omnis</h4>
          <h2>Quaerat suscipit unde minus dicta</h2>
        </div>
      </div>
    </div>
  </div>
    <!-- Banner Ends Here -->

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Submit</button>
    </form>


{% endblock %}

templates/owner_panel/Vehical_Details.html
{% extends 'owner_panel/base.html' %}
{% load static %}

{% block main %}

<!-- Banner Starts Here -->

<div class="banner header-text">
    <div class="owl-banner owl-carousel">
      <div class="banner-item-01">
        <div class="text-content">
          <h4>Find your car today!</h4>
          <h2>Lorem ipsum dolor sit amet</h2>
        </div>
      </div>
      <div class="banner-item-02">
        <div class="text-content">
          <h4>Fugiat Aspernatur</h4>
          <h2>Laboriosam reprehenderit ducimus</h2>
        </div>
      </div>
      <div class="banner-item-03">
        <div class="text-content">
          <h4>Saepe Omnis</h4>
          <h2>Quaerat suscipit unde minus dicta</h2>
        </div>
      </div>
    </div>
  </div>
    <!-- Banner Ends Here -->

    
    <table class="table">
        <thead class="table-dark" style="border-radius: 25px;">
            <tr>
                
                <th scope="col">vehical_Variant</th>
                <th scope="col">Vehical_Number</th>
                <th scope="col">Model_Year</th>
                <th scope="col">KM_reading</th>
                <th scope="col">Vehical_Orignal_img</th>
                <th scope="col">Prize Per Day</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
          {% for i in data %}
            <tr class="shadow p-3 mb-5 bg-body rounded" >
                
                <td>{{ i.vehical_Variant }}</td>
                <td>{{ i.Vehical_Number }}</td>
                <td>{{ i.Model_Year }}</td>
                <td>{{ i.KM_reading }}</td>
                <td>
                    {% if data.Vehical_Orignal_img %}
                    <img src="{{ i.Vehical_Orignal_img.url }}" style="height: 50px;" class="rounded" alt="">
                    {% else %}
                    No Img
                    {% endif %}
                </td>
                
                <td>{{ i.Prize }}</td>
                <td>{{ i.Status }}</td>
                <td>{{ i.Action }}              
                <a class="btn btn-danger" href="{% url 'owner_panel:delete_vehicle' i.id %}" role="button">Delete</a>               
              </td>   
            </tr>
            {% endfor %}
            
        </tbody>
    </table>

{% endblock %}

templates/owner_panel/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="assets/images/favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <title></title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/user_css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'css/user_css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/user_css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/user_css/owl.css' %}">

    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css"/>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous" />

    <!-- or -->
    <link
      rel="stylesheet"
      href="https://unpkg.com/boxicons@latest/css/boxicons.min.css"/>
    <meta http-equiv="Content-Language" content="en" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="msapplication-tap-highlight" content="no" />

    {% block head %}
    {% endblock %}

  </head>

  <body>

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->

    <!-- Header -->
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="index.html"><h2>Vehicle Rental <em>Website</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'owner_panel:home' %}">Home
                      <span class="sr-only">(current)</span>
                    </a>
                </li> 

                <li class="nav-item"><a class="nav-link" href="{% url 'owner_panel:Rent_Vehical' %}">Put On Rent</a></li>
                
                <li class="nav-item"><a class="nav-link" href="{% url 'owner_panel:ownervehicledetails' %}">Vehicle Details</a></li>
                

                
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout_user' %}">Logout</a></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    


    {% block main %}
    {% endblock %}
    


    




    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'js/user_js/jquery.min.js' %}"></script>
    <script src="{% static 'js/user_js/bootstrap.bundle.min.js' %}"></script>


    <!-- Additional Scripts -->
    <script src="{% static 'js/user_js/custom.js' %}"></script>
    <script src="{% static 'js/user_js/owl.js' %}"></script>
  </body>
</html>

templates/owner_panel/home.html
{% extends 'owner_panel/base.html' %}
{% load static %}

{% block head %}
<style>
    .banner {
	position: relative;
	text-align: center;
	padding-top: 80px;
}

.banner-item-01 {
	padding: 300px 0px;
	background-image: url(../../static/images/user_panel/slider-image-3-1920x600.jpg);
	background-size: cover;
	background-repeat: no-repeat;
	background-position: center center;
}

.banner-item-02 {
	padding: 300px 0px;
	background-image: url(../../static/images/user_panel/slider-image-2-1920x600.jpg);
	background-size: cover;
	background-repeat: no-repeat;
	background-position: center center;
}

.banner-item-03 {
	padding: 300px 0px;
	background-image: url(../../static/images/user_panel/slider-image-1-1920x600.jpg);
	background-size: cover;
	background-repeat: no-repeat;
	background-position: center center;
}

.banner .banner-item {
	max-height: 600px;
}

.banner .text-content {
	position: absolute;
	top: 50%;
	transform: translateY(-50%);
	text-align: center;
	width: 100%;
}

.banner .text-content h4 {
	color: #f33f3f;
	font-size: 22px;
	text-transform: uppercase;
	font-weight: 700;
	margin-bottom: 15px;
}

.banner .text-content h2 {
	color: #fff;
	font-size: 62px;
	text-transform: uppercase;
	letter-spacing: 5px;
}

.owl-banner .owl-dots .owl-dot {
  border-radius: 3px;
}
.owl-banner .owl-dots {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-pack: center;
    -webkit-justify-content: center;
    justify-content: center;
    position: absolute;
    left: 50%;
    transform: translateX(-50%);
    bottom: 30px;
}
.owl-banner .owl-dots .owl-dot {
    width: 10px;
    height: 10px;
    border-radius: 50%;
    margin: 0 10px;
    background-color: #fff;
    opacity: 0.5;
}
.owl-banner .owl-dots .owl-dot:focus {
    outline: none
}
.owl-banner .owl-dots .owl-dot.active {
    background-color: #fff;
    opacity: 1;
}
</style>
    {% endblock %}

{% block main %}

<!-- Banner Starts Here -->

<div class="banner header-text">
    <div class="owl-banner owl-carousel">
      <div class="banner-item-01">
        <div class="text-content">
          <h4>PUT YOUR VEHICLE ON RENT</h4>
          <h2>GET PAID</h2>
        </div>
      </div>
      <div class="banner-item-02">
        <div class="text-content">
          <h4>FIND THE COUSTOMER EASILY</h4>
          <h2>A LOT OF CITY AVALILABLE</h2>
        </div>
      </div>
      <div class="banner-item-03">
        <div class="text-content">
          <h4>BEST SERVICES</h4>
          <h2>FULL FUNCTIONAL SYSTEM</h2>
        </div>
      </div>
    </div>
  </div>
    <!-- Banner Ends Here -->





{% endblock %}