accounts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = "accounts"

urlpatterns = [
    path('', views.demo, name='demo'),
    path('login/', views.login_page, name='login_page'),

    path('user_signup/', views.user_signup, name='user_signup'),
    path('admin_signup/', views.admin_signup, name='admin_signup'),
    path('owner_signup/', views.owner_signup, name='owner_signup'),

    path('logout_user/', views.logout_user, name='logout_user'),




] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user_panel/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = "user_panel"

urlpatterns = [
    
    path('home/', views.home, name='home'),

    path('Available_Vehical/', views.Available_Vehical, name='Available_Vehical'),
    path('type_wise_filter_in_userpanel/<int:id>', views.type_wise_filter_in_userpanel, name='type_wise_filter_in_userpanel'),
    path('city_wise_search/<str:state>', views.City_filter_in_userpanel, name='City_filter_in_userpanel'),

    path('Team', views.Team, name='Team'),
    
    
    path('Rent_Request/<int:id>/', views.Rent_Request, name='Rent_Request'),







   
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

vehicalrental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('admin_panel/', include('admin_panel.urls')),
    path('owner_panel/', include('owner_panel.urls')),
    path('user_panel/', include('user_panel.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_panel/models.py
from django.db import models
from accounts.models import *
from admin_panel.models import *

# Create your models here.

Status = (
    ('Pending', 'Pending'),
    ('Available','Available'),
)

class VehicalRequest(models.Model):
    UserId = models.ForeignKey(User, on_delete=models.CASCADE)
    VehicalId = models.ForeignKey(Vehical_Registration, on_delete=models.CASCADE)
    RequestDate = models.DateTimeField(auto_now_add=True)
    StartDate = models.DateField()
    EndDate = models.DateField()
    Pickup = models.CharField(max_length=20)
    Drop = models.CharField(max_length=20)
    Total_Price = models.IntegerField()
    Addhar_img = models.ImageField(upload_to='User_Addhar_img')
    Status = models.CharField(max_length=50, choices=Status, default='Pending')

    def __str__(self):
        return self.UserId

user_panel/forms.py
from dataclasses import field
from tkinter import Widget
from .models import VehicalRequest
from django import forms


class VehicalRequestForm(forms.ModelForm):
    class Meta:
        model  = VehicalRequest
        fields = '__all__'
        exclude = ('UserId', 'RequestDate','VehicalId', 'Status', 'Total_Price')
        widgets = {
            'StartDate': forms.DateInput(attrs={
                'type':'date',
                'placeholder': 'Enter your First name',
                'class':'mb-3 form-control',
            }),
        
            'EndDate': forms.DateInput(attrs={
                'type':'date',
                'class':'mb-3 form-control',

                    'placeholder': 'Enter your Last name',
                }),

            'Pickup': forms.TextInput(attrs={
                    'placeholder': 'Enter your Last name',
                    'class':'mb-3 form-control',

                }),

            'Drop': forms.TextInput(attrs={
                    'placeholder': 'Enter your Last name',
                    'class':'mb-3 form-control',
                    
                }),
            
            
            



        }

user_panel/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib import messages
from .models import *
from django.urls import reverse
from .forms import *
from user_panel.models import *
import datetime


# Create your views here.

def home(request):
    return render(request, 'user_panel/home.html')

def Team(request):
    return render(request, "user_panel/Team.html")

def Available_Vehical(request):
    # data = Vehical_Registration.objects.all().exclude(UserId=request.user.id)
    types = VehicalType.objects.all()
    city = User.objects.all().values('State').distinct()
    data = Vehical_Registration.objects.filter(Status="Accepted").exclude(UserId=request.user.id)
    return render(request, 'user_panel/Available_Vehical.html', {'data' : data, 'types' : types, 'city' : city })


def type_wise_filter_in_userpanel(request,id):
    data = Vehical_Registration.objects.filter(Vahical_Type=id)
    types = VehicalType.objects.all()
    return render(request, 'user_panel/Available_Vehical.html', {'data' : data, 'types': types})

def City_filter_in_userpanel(request,state):
    
    types = VehicalType.objects.all()

    data = Vehical_Registration.objects.filter(UserId__State=state, Status="Accepted").exclude(UserId=request.user.id)
    print(data)
    return render(request, 'user_panel/Available_Vehical.html', {'data' : data, 'types': types})



def Rent_Request(request, id):
    
    r_vehicale=Vehical_Registration.objects.get(id=id)
    if request.method == 'POST':
        form = VehicalRequestForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.save(commit=False)
            data.UserId=request.user
            data.VehicalId=r_vehicale
            delta = datetime.datetime.strptime(request.POST['EndDate'], "%Y-%m-%d") - datetime.datetime.strptime(request.POST['StartDate'], "%Y-%m-%d")
            data.Total_Price = delta.days * r_vehicale.Prize
            data.save()
            return HttpResponseRedirect(reverse('user_panel:home'))
        else:
            print(form.errors)
    else:
        form = VehicalRequestForm()
        abcd = VehicalRequest.objects.all()
    return render(request, 'user_panel/Rent_Request.html', {'form': form, 'data' : abcd, 'r_vehicale' : r_vehicale })

templates/user_panel/Available_Vehical.html
{% extends 'user_panel/base.html' %}
{% load static %}

{% block title %}

Available Vehical

{% endblock %}

{% block head %}
<!-- <style>
    .abcd{
        padding-top: 500px;
    }
</style> -->
    {% endblock %}

{% block main %}

    <!-- Banner Starts Here -->

<div class="banner header-text">
    <div class="owl-banner owl-carousel">
      <div class="banner-item-01">
        <div class="text-content">
          <h4>Find your car today!</h4>
          <h2>Lorem ipsum dolor sit amet</h2>
        </div>
      </div>
      <div class="banner-item-02">
        <div class="text-content">
          <h4>Fugiat Aspernatur</h4>
          <h2>Laboriosam reprehenderit ducimus</h2>
        </div>
      </div>
      <div class="banner-item-03">
        <div class="text-content">
          <h4>Saepe Omnis</h4>
          <h2>Quaerat suscipit unde minus dicta</h2>
        </div>
      </div>
    </div>
  </div>
    <!-- Banner Ends Here -->
    <!-- <h1>Available Vehical</h1> -->
    <br>

    {% for i in types %}
        <a href="{% url 'user_panel:type_wise_filter_in_userpanel' i.id %}" type="button" class="btn btn-outline-dark"> {{ i.Type_Name }} </a>
    {% endfor %}
        <br>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Select City</a>
          
          <div class="dropdown-menu">
            {% for i in city %}
              <a class="dropdown-item" href="../../user_panel/city_wise_search/{{i.State}}">{{i.State}}</a>
            {% endfor %}                     
            
          </div>
      </li>
        
    <!-- <table class="table">
        <thead class="table-dark" style="border-radius: 25px;">
            <tr>
                <th scope="col">NO.</th>
                <th scope="col">vehical_Variant</th>
                <th scope="col">Vehical_Number</th>
                <th scope="col">Model_Year</th>
                <th scope="col">KM_reading</th>
                <th scope="col">Vehical_Orignal_img</th>
                <th scope="col">Prize Per Day</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for i in data %}
            <tr class="shadow p-3 mb-5 bg-body rounded" >
                <td scope="row">{{ forloop.counter }}</td>
                <td>{{ i.vehical_Variant }}</td>
                <td>{{ i.Vehical_Number }}</td>
                <td>{{ i.Model_Year }}</td>
                <td>{{ i.KM_reading }}</td>
                <td>
                    {% if i.Vehical_Orignal_img %}
                    <img src="{{ i.Vehical_Orignal_img.url }}" style="height: 50px;" class="rounded" alt="">
                    {% else %}
                    No Img
                    {% endif %}
                </td>
                
                <td>{{ i.Prize }}</td>
                <td>{{ i.Action }}

                  <a class="btn btn-secondary" href="{% url 'user_panel:Rent_Request' i.id  %}" role="button">Request Rent</a>
                 
              </td>
                
            
            </tr>
            {% endfor %}
        </tbody>
    </table> -->



    <div class="products ">
      <div class="container ">
        <div class="row ">
    {% for i in data %}
    
          <div class="col-md-4 shadow p-3 mb-5 bg-body rounded">
            <a  href="{% url 'user_panel:Rent_Request' i.id  %}" >
            <div class="product-item">
              <img src="{{ i.Vehical_Orignal_img.url }}" alt="">

              <div class="down-content">
                <h4>{{ i.vehical_Variant }}</h4>
                  
                <h6> {{ i.Prize }}₹ <small>Per Day</small></h6>

                

                <small>
                    <!-- <strong title="passegengers"><i class="fa fa-user"></i> {{ i.vehical_Variant }} </strong> &nbsp;&nbsp;&nbsp; -->
                    <!-- <strong title="luggages"><i class="fa fa-briefcase"></i> {{ i.Vehical_Number }}</strong> &nbsp;&nbsp;&nbsp; -->
                    <!-- <strong title="doors"><i class="fa fa-sign-out"></i> {{ i.Model_Year }}</strong> &nbsp;&nbsp;&nbsp; -->
                    <!-- <strong title="transmission"><i class="fa fa-cog"></i> {{ i.KM_reading }}</strong> -->
                </small>

                <span>
                  <a href="#" data-toggle="modal" data-target="#exampleModal">Book Now</a>
                </span>
              </div>
            </div>
          </a>  
          </div>     
          
          {% endfor %}
        </div>
      </div>
    </div>

   
        
{% endblock %}









        
 

templates/user_panel/Rent_Request.html
{% extends 'user_panel/base.html' %}
{% load static %}

{% block head %}
<!-- <style>
    .abcd{
        padding-top: 500px;
    }
</style> -->
    {% endblock %}

{% block main %}

    <!-- Banner Starts Here -->

<div class="banner header-text">
    <div class="owl-banner owl-carousel">
      <div class="banner-item-01">
        <div class="text-content">
          <h4>Find your car today!</h4>
          <h2>Lorem ipsum dolor sit amet</h2>
        </div>
      </div>
      <div class="banner-item-02">
        <div class="text-content">
          <h4>Fugiat Aspernatur</h4>
          <h2>Laboriosam reprehenderit ducimus</h2>
        </div>
      </div>
      <div class="banner-item-03">
        <div class="text-content">
          <h4>Saepe Omnis</h4>
          <h2>Quaerat suscipit unde minus dicta</h2>
        </div>
      </div>
    </div>
  </div>
    <!-- Banner Ends Here -->


    
    <h1>Available_Vehical</h1>
    <br>
    <table class="table">
        <thead class="table-dark" style="border-radius: 25px;">
            <tr>
                
                <th scope="col">vehical_Variant</th>
                <th scope="col">Vehical_Number</th>
                <th scope="col">Model_Year</th>
                <th scope="col">KM_reading</th>
                <th scope="col">Vehical_Orignal_img</th>
                <th scope="col">Prize Per Day</th>
                
            </tr>
        </thead>
        <tbody>
            
            <tr class="shadow p-3 mb-5 bg-body rounded" >
               
                <td>{{ r_vehicale.vehical_Variant }}</td>
                <td>{{ r_vehicale.Vehical_Number }}</td>
                <td>{{ r_vehicale.Model_Year }}</td>
                <td>{{ r_vehicale.KM_reading }}</td>
                <td>
                    {% if r_vehicale.Vehical_Orignal_img %}
                    <img src="{{ r_vehicale.Vehical_Orignal_img.url }}" style="height: 50px;" class="rounded" alt="">
                    {% else %}
                    No Img
                    {% endif %}
                </td>
                
                <td>{{ r_vehicale.Prize }}</td>
                
                 
              </td>
                
            
            </tr>
        </tbody>
    </table>

    <br>
    <br>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- {{form}}       -->
    

    <div class="mb-3">
      <label for="exampleFormControlInput1" class="form-label">start date</label>
      {{ form.StartDate}}
    </div>
    <div class="mb-3">
      <label for="exampleFormControlInput1" class="form-label">End date</label>
      {{ form.EndDate}}
    </div>
    <div class="mb-3">
      <label for="exampleFormControlInput1" class="form-label">Pickup</label>
      {{ form.Pickup}}
    </div>
    <div class="mb-3">
      <label for="exampleFormControlInput1" class="form-label">Drop</label>
      {{ form.Drop}}
    </div>
    <div class="mb-3">
      <label for="exampleFormControlInput1" class="form-label">Addhar img</label>
      {{ form.Addhar_img}}
    </div>
    <button type="submit"> Submit</button>
  </form>

    {% endblock %}

templates/user_panel/Team.html
{% extends 'user_panel/base.html' %}
{% load static %}

  {% block main %}
    <!-- Page Content -->
    <div class="page-heading about-heading header-text" style="background-image: url(../../static/images/user_panel/heading-1-1920x500.jpg);">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="text-content">
              <!-- <h4>Lorem ipsum dolor</h4> -->
              <h2>Our Team Members</h2>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="team-members">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <div class="team-member">
              <div class="thumb-container">
                <img src="{% static 'images\user_panel\dhruv.jpeg' %}" alt="">
                <div class="hover-effect">
                  <div class="hover-content">
                    <ul class="social-icons">
                      <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                      <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                      <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                      <li><a href="#"><i class="fa fa-behance"></i></a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="down-content">
                <h4>Dhruvkumar Busa</h4>
                <span>CO-Founder</span>
                <p></p>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="team-member">
              <div class="thumb-container">
                <img src="{% static 'images\user_panel\krishna.jpg' %}" alt="">
                <div class="hover-effect">
                  <div class="hover-content">
                    <ul class="social-icons">
                      <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                      <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                      <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                      <li><a href="#"><i class="fa fa-behance"></i></a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="down-content">
                <h4>KRishna Dobariya</h4>
                <span>Product Expert</span>
                <p></p>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="team-member">
              <div class="thumb-container">
                <img src="{% static 'images\user_panel\nishant.jpeg' %}" alt="">
                <div class="hover-effect">
                  <div class="hover-content">
                    <ul class="social-icons">
                      <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                      <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                      <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                      <li><a href="#"><i class="fa fa-behance"></i></a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="down-content">
                <h4>Nishant Patel</h4>
                <span>Chief Marketing</span>
                <p></p>
              </div>
            </div>
          </div>
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="inner-content">
              <p> <a href="https://www.phpjabbers.com/"></a></p>
            </div>
          </div>
        </div>
      </div>
    </footer>
  {% endblock %}

templates/user_panel/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static '/images/user_panel/favicon.ico' %}">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <title>{% block title %}
      {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/user_css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'css/user_css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/user_css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/user_css/owl.css' %}">

    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css"/>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous" />

    <!-- or -->
    <link
      rel="stylesheet"
      href="https://unpkg.com/boxicons@latest/css/boxicons.min.css"/>
    <meta http-equiv="Content-Language" content="en" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="msapplication-tap-highlight" content="no" />

    {% block head %}
    {% endblock %}

  </head>

  <body>

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->

    <!-- Header -->
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="index.html"><h2>Vehical Rental <em>Website</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'user_panel:home' %}">Home
                      <span class="sr-only">(current)</span>
                    </a>
                </li> 

                <li class="nav-item"><a class="nav-link" href="{% url 'user_panel:Available_Vehical' %}">Vehicles</a></li>
                

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">More</a>
                    
                    <div class="dropdown-menu">
                      
                      <a class="dropdown-item" href="{% url 'user_panel:Team' %}">Team</a>
                    </div>
                </li>

                <li class="nav-item"><a class="nav-link" href="about-us.html">About Us</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:owner_signup' %}">Become a Host</a></li>
                
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout_user' %}">Logout</a></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    


    {% block main %}
    {% endblock %}
    


    




    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'js/user_js/jquery.min.js' %}"></script>
    <script src="{% static 'js/user_js/bootstrap.bundle.min.js' %}"></script>


    <!-- Additional Scripts -->
    <script src="{% static 'js/user_js/custom.js' %}"></script>
    <script src="{% static 'js/user_js/owl.js' %}"></script>
  </body>
</html>

templates/user_panel/home.html
{% extends 'user_panel/base.html' %}
{% load static %}

{% block head %}
<style>
    .banner {
	position: relative;
	text-align: center;
	padding-top: 80px;
}

.banner-item-01 {
	padding: 300px 0px;
	background-image: url(../../static/images/user_panel/slider-image-1-1920x600.jpg);
	background-size: cover;
	background-repeat: no-repeat;
	background-position: center center;
}

.banner-item-02 {
	padding: 300px 0px;
	background-image: url(../../static/images/user_panel/slider-image-2-1920x600.jpg);
	background-size: cover;
	background-repeat: no-repeat;
	background-position: center center;
}

.banner-item-03 {
	padding: 300px 0px;
	background-image: url(../../static/images/user_panel/slider-image-3-1920x600.jpg);
	background-size: cover;
	background-repeat: no-repeat;
	background-position: center center;
}

.banner .banner-item {
	max-height: 600px;
}

.banner .text-content {
	position: absolute;
	top: 50%;
	transform: translateY(-50%);
	text-align: center;
	width: 100%;
}

.banner .text-content h4 {
	color: #f33f3f;
	font-size: 22px;
	text-transform: uppercase;
	font-weight: 700;
	margin-bottom: 15px;
}

.banner .text-content h2 {
	color: #fff;
	font-size: 62px;
	text-transform: uppercase;
	letter-spacing: 5px;
}

.owl-banner .owl-dots .owl-dot {
  border-radius: 3px;
}
.owl-banner .owl-dots {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-pack: center;
    -webkit-justify-content: center;
    justify-content: center;
    position: absolute;
    left: 50%;
    transform: translateX(-50%);
    bottom: 30px;
}
.owl-banner .owl-dots .owl-dot {
    width: 10px;
    height: 10px;
    border-radius: 50%;
    margin: 0 10px;
    background-color: #fff;
    opacity: 0.5;
}
.owl-banner .owl-dots .owl-dot:focus {
    outline: none
}
.owl-banner .owl-dots .owl-dot.active {
    background-color: #fff;
    opacity: 1;
}
</style>
    {% endblock %}

{% block main %}

    <!-- Banner Starts Here -->

<div class="banner header-text">
    <div class="owl-banner owl-carousel">
      <div class="banner-item-01">
        <div class="text-content">
          <h4>FIND YOUR VEHICLE TODAY</h4>
          <h2>BOOK THE BEST VEHICLE FOR YOU</h2>
        </div>
      </div>
      <div class="banner-item-02">
        <div class="text-content">
          <h4>FIND THE BEST VARIANT</h4>
          <h2>A LOT OF VARIANTS AVALILABLE</h2>
        </div>
      </div>
      <div class="banner-item-03">
        <div class="text-content">
          <h4>BEST SERVICES</h4>
          <h2>FULL FUNCTIONAL SYSTEM</h2>
        </div>
      </div>
    </div>
  </div>
    <!-- Banner Ends Here -->

        
        
{% endblock %}