accounts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = "accounts"

urlpatterns = [
    path('', views.demo, name='demo'),
    path('login/', views.login_page, name='login_page'),

    path('user_signup/', views.user_signup, name='user_signup'),
    path('admin_signup/', views.admin_signup, name='admin_signup'),
    path('owner_signup/', views.owner_signup, name='owner_signup'),

    path('logout_user/', views.logout_user, name='logout_user'),




] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin_panel/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = "admin_panel"

urlpatterns = [
    path('home/', views.home, name='home'),
    
    path('Users/', views.Users, name='Users'),
    path('deleteUsers/<int:id>/', views.deleteUsers, name='deleteUsers'),

    path('create_type/', views.create_type, name='create_type'),
    path('updatetype/<int:id>', views.updatetype, name="updatetype"),
    path('deletetype/<int:id>', views.deletetype, name="deletetype"),

    path('brand/', views.addbrand, name='addbrand'),    
    path('updatebrand/<int:id>', views.updatebrand, name="updatebrand"),
    path('deletebrand/<int:id>', views.deletebrand, name="deletebrand"),


    path('category/', views.category, name='category'),
    path('type_wise_category/<int:id>', views.type_wise_category, name='type_wise_category'),
    path('updatecategory/<int:id>', views.updatecategory, name="updatecategory"),
    path('deletecategory/<int:id>', views.deletecategory, name="deletecategory"),

    path('Vehical_Variant/', views.Vehical_Variant, name='Vehical_Variant'),
    path('type_wise_category_in_variant/<int:id>', views.type_wise_category_in_variant, name='type_wise_category_in_variant'),
    path('Add_Vehical_Variant/', views.Add_Vehical_Variant, name='Add_Vehical_Variant'),
    path('updatevariant/<int:id>', views.updatevariant, name="updatevariant"),
    path('deletevariant/<int:id>', views.deletevariant, name="deletevariant"),

    path('vehical_Registration/', views.vehical_Registration, name='vehical_Registration'),
    path('type_wise_filter_in_registration/<int:id>', views.type_wise_filter_in_registration, name='type_wise_filter_in_registration'),
    path('Register_Vehical_List/', views.Register_Vehical_List, name='Register_Vehical_List'),
    path('update_Register_Vehical/<int:id>', views.update_Register_Vehical, name="update_Register_Vehical"),
    path('delete_Register_Vehical/<int:id>', views.delete_Register_Vehical, name="delete_Register_Vehical"),


    path('owner_rq_List/', views.owner_rq_List, name='owner_rq_List'),
    path('accept_owner_req/<int:id>', views.accept_owner_req, name='accept_owner_req'),
    path('reject_owner_req/<int:id>', views.reject_owner_req, name='reject_owner_req'),

    path('Rent_Rq_List_admin/', views.Rent_Rq_List_admin, name='Rent_Rq_List_admin'),
    path('accept_rent_req/<int:id>', views.accept_rent_req, name='accept_rent_req'),
    path('reject_rent_req/<int:id>', views.reject_rent_req, name='reject_rent_req'),

    path('Available_Vehical_List/', views.Available_Vehical_List, name='Available_Vehical_List'),
    path('type_wise_filter_in_Available_Vehical/<int:id>', views.type_wise_filter_in_Available_Vehical, name='type_wise_filter_in_Available_Vehical'),



   
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

vehicalrental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('admin_panel/', include('admin_panel.urls')),
    path('owner_panel/', include('owner_panel.urls')),
    path('user_panel/', include('user_panel.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin_panel/forms.py
from dataclasses import field
from tkinter import Widget
from .models import VehicalType,brand,category_list,vehical_Variant,Vehical_Registration
from django import forms


class VehicalTypeForm(forms.ModelForm):
    class Meta:
        model  = VehicalType
        fields = '__all__'
        exclude = ('added_date',)

class brandform(forms.ModelForm):
    class Meta:
        model  = brand
        fields = '__all__'
        exclude = ('AddDate','UserId')

class category_listform(forms.ModelForm):
    class Meta:
        model  = category_list
        fields = '__all__'
        exclude = ('AddDate','UserId')

        
class vehical_Variantform(forms.ModelForm):
    class Meta:
        model  = vehical_Variant
        fields = '__all__'
        exclude = ('AddDate','UserId')

class Vehical_Registrationform(forms.ModelForm):
    class Meta:
        model  = Vehical_Registration
        fields = '__all__'
        exclude = ('AddDate','UserId', 'Owner_Driving_Licence', 'RCBOOK')

admin_panel/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib import messages
from .models import *
from django.urls import reverse
from .forms import *
from user_panel.models import *

# from django.contrib.auth import authenticate, login, logout




# Create your views here.

def home(request):
    return render(request, 'admin_panel/home.html')

def create_type(request):
    if request.method == 'POST':
        form = VehicalTypeForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_panel:create_type'))
        else:
            print(form.errors)
    else:
        form = VehicalTypeForm()
        data = VehicalType.objects.all()
    return render(request, 'admin_panel/vehical_type.html', {'form': form, 'data' : data})


def updatetype(request, id):
    details = VehicalType.objects.get(id=id)
    form_v = VehicalTypeForm(instance=details)
    if request.method == "POST":
        form_v = VehicalTypeForm(request.POST, instance=details)
        if form_v.is_valid():
            user = form_v.save()
            user.save()
            return redirect("admin_panel:create_types")
        else:
            print(form_v.errors)
    return render(request, "admin_panel/vehical_type.html", {'form' : form_v})


def deletetype(request, id):
  details = VehicalType.objects.get(id=id)
  details.delete()
  return redirect("admin_panel:create_type")





def addbrand(request):
    if request.method == 'POST':
        form = brandform(request.POST, request.FILES)
        if form.is_valid():
            
            data = form.save(commit=False)
            data.UserId=request.user
            data.save()
            return HttpResponseRedirect(reverse('admin_panel:addbrand'))
        else:
            print(form.errors)
    else:
        form = brandform()
        form = brandform()
        data = brand.objects.all()
    return render(request, 'admin_panel/vehical_brand.html', {'form': form,  'data' : data})



def updatebrand(request, id):
    details = brand.objects.get(id=id)
    form_v = brandform(instance=details)
    if request.method == "POST":
        form_v = brandform(request.POST, instance=details)
        if form_v.is_valid():
            user = form_v.save()
            user.save()
            return redirect("admin_panel:addbrand")
        else:
            print(form_v.errors)
    return render(request, "admin_panel/vehical_brand.html", {'form' : form_v})


def deletebrand(request, id):
  details = brand.objects.get(id=id)
  details.delete()
  return redirect("admin_panel:addbrand")



def category(request):
    if request.method == 'POST':
        form = category_listform(request.POST, request.FILES)
        if form.is_valid():
            data = form.save(commit=False)
            data.UserId=request.user
            data.save()
            return HttpResponseRedirect(reverse('admin_panel:category'))
        else:
            print(form.errors)
    else:
        form = category_listform()
        data = category_list.objects.all()
        types = VehicalType.objects.all()
    return render(request, 'admin_panel/vehical_category.html', {'form': form, 'data' : data, 'types': types})

def type_wise_category(request, id):
    
    if request.method == 'POST':
        form = category_listform(request.POST, request.FILES)
        if form.is_valid():
            data = form.save(commit=False)
            data.UserId=request.user
            data.save()
            return HttpResponseRedirect(reverse('admin_panel:category'))
        else:
            print(form.errors)

    else:
        form = category_listform()
        data = category_list.objects.filter(Vehical_TypeID=id)
        types = VehicalType.objects.all()
        return render(request, 'admin_panel/vehical_category.html', {'form': form, 'data' : data, 'types': types})


def updatecategory(request, id):
    details = category_list.objects.get(id=id)
    form_v = category_listform(instance=details)
    if request.method == "POST":
        form_v = category_listform(request.POST, instance=details)
        if form_v.is_valid():
            user = form_v.save()
            user.save()
            return redirect("admin_panel:category")
        else:
            print(form_v.errors)
    return render(request, "admin_panel/vehical_category.html", {'form' : form_v})


def deletecategory(request, id):
    details = category_list.objects.get(id=id)
    details.delete()
    return redirect("admin_panel:category")





def Add_Vehical_Variant(request):
    if request.method == 'POST':
        form = vehical_Variantform(request.POST, request.FILES)
        if form.is_valid():
            data = form.save(commit=False)
            data.UserId=request.user
            data.save()
            return HttpResponseRedirect(reverse('admin_panel:Vehical_Variant'))
        else:
            print(form.errors)
    else:
        form = vehical_Variantform()
        data = vehical_Variant.objects.all()        
    return render(request, 'admin_panel/Add_Variant.html', {'form': form, 'data' : data})

def type_wise_category_in_variant(request, id):
    if request.method == 'POST':
        form = vehical_Variantform(request.POST, request.FILES)
        if form.is_valid():
            data = form.save(commit=False)
            data.UserId=request.user
            data.save()
            return HttpResponseRedirect(reverse('admin_panel:Vehical_Variant'))
        else:
            print(form.errors)
    else:
        form = vehical_Variantform()
        data = vehical_Variant.objects.filter(Vahical_Type=id)
        types = VehicalType.objects.all()
        return render(request, 'admin_panel/Vehical_Variant.html', {'form': form, 'data' : data, 'types': types})



def Vehical_Variant(request):
    form = vehical_Variantform()
    types = VehicalType.objects.all()
    data = vehical_Variant.objects.all()
    return render(request, 'admin_panel/Vehical_Variant.html', { 'data' : data, 'types': types, 'form': form })
    

def updatevariant(request, id):
    details = vehical_Variant.objects.get(id=id)
    form_v = vehical_Variantform(instance=details)
    if request.method == "POST":
        form_v = vehical_Variantform(request.POST, instance=details)
        if form_v.is_valid():
            user = form_v.save()
            user.save()
            return redirect("admin_panel:Vehical_Variant")
        else:
            print(form_v.errors)
    return render(request, "admin_panel/Add_Variant.html", {'form' : form_v})


def deletevariant(request, id):
    details = vehical_Variant.objects.get(id=id)
    details.delete()
    return redirect("admin_panel:Vehical_Variant")


def vehical_Registration(request):
    if request.method == 'POST':
        form = Vehical_Registrationform(request.POST, request.FILES)
        if form.is_valid():
            data = form.save(commit=False)
            data.UserId=request.user
            data.Status = "Accepted"
            data.save()
            return HttpResponseRedirect(reverse('admin_panel:Register_Vehical_List'))
        else:
            print(form.errors)
    else:
        form = Vehical_Registrationform()
        data = Vehical_Registration.objects.all()
    return render(request, 'admin_panel/Vehical_Registration.html', {'form': form, 'data' : data})

def type_wise_filter_in_registration(request,id):
    if request.method == 'POST':
        form = Vehical_Registrationform(request.POST, request.FILES)
        if form.is_valid():
            data = form.save(commit=False)
            data.UserId=request.user
            data.save()
            return HttpResponseRedirect(reverse('admin_panel:Register_Vehical_List'))
        else:
            print(form.errors)
    else:
        form = Vehical_Registrationform()
        types = VehicalType.objects.all()
        data = Vehical_Registration.objects.filter(Vahical_Type=id)
        return render(request, 'admin_panel/Register_Vehical_List.html', {'form': form, 'data' : data, 'types' : types})


def Register_Vehical_List(request):
    types = VehicalType.objects.all()
    data = Vehical_Registration.objects.all()
    return render(request, 'admin_panel/Register_Vehical_List.html', {'data' : data, 'types': types})


def update_Register_Vehical(request, id):
    details = Vehical_Registration.objects.get(id=id)
    form_v = Vehical_Registrationform(instance=details)
    if request.method == "POST":
        form_v = Vehical_Registrationform(request.POST, instance=details)
        if form_v.is_valid():
            user = form_v.save()
            user.save()
            return redirect("admin_panel:Register_Vehical_List")
        else:
            print(form_v.errors)
    return render(request, "admin_panel/Vehical_Registration.html", {'form' : form_v})


def delete_Register_Vehical(request, id):
    details = Vehical_Registration.objects.get(id=id)
    details.delete()
    return redirect("admin_panel:Register_Vehical_List")





def Users(request):
    data = User.objects.all()
    return render(request, 'admin_panel/user_details.html', {'data' : data})

def deleteUsers(request, id):
    details = User.objects.get(id=id)
    details.delete()
    return redirect("admin_panel:Users")


def owner_rq_List(request):
    data = Vehical_Registration.objects.all().exclude(UserId=request.user.id)
    # data = Vehical_Registration.objects.filter(UserId=request.user.id, Status="Available")
    return render(request, 'admin_panel/owner_Rq_List.html', {'data' : data})

def accept_owner_req(request, id):
    data = Vehical_Registration.objects.get(id=id)
    data.Status = "Accepted"
    data.save()
    return redirect("admin_panel:owner_rq_List")

def reject_owner_req(request, id):
    data = Vehical_Registration.objects.get(id=id)
    data.Status = "Rejected"
    data.save()
    return redirect("admin_panel:owner_rq_List")
    



def Rent_Rq_List_admin(request):

templates/admin_panel/Register_Vehical_List.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block head %}
    
<style>
    /* .table{
        background-color: rgb(33, 152, 199) !important;
        border-radius: 25px;
    } */
        
    
    
</style>

      {% endblock %}

    {% block main %}
    

    

    <a class="btn btn-danger" href="{% url 'admin_panel:vehical_Registration' %}">Register New Vehical</a>

    <br>
    <br>

    {% for i in types %}
        <a href="{% url 'admin_panel:type_wise_filter_in_registration' i.id %}" type="button" class="btn btn-outline-dark"> {{ i.Type_Name }} </a>
    {% endfor %}

    <h1>List Of Register Vehical</h1>
    <br>
    <table class="table">
        <thead class="table-dark" style="border-radius: 25px;">
            <tr>
                <th scope="col">NO.</th>
                <th scope="col">vehical_Variant</th>
                <th scope="col">Vehical_Number</th>
                <th scope="col">Model_Year</th>
                <th scope="col">KM_reading</th>
                <th scope="col">Vehical_Orignal_img</th>
                <th scope="col">Status</th>
                <th scope="col">Prize Per Day</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for i in data %}
            <tr class="shadow p-3 mb-5 bg-body rounded" >
                <td scope="row">{{ forloop.counter }}</td>
                <!-- <td><img src="{{i.Variant_Photo.url}}" class="img" alt=""> -->
                <td>{{ i.vehical_Variant }}</td>
                <td>{{ i.Vehical_Number }}</td>
                <td>{{ i.Model_Year }}</td>
                <td>{{ i.KM_reading }}</td>
                <td><img src="{{ i.Vehical_Orignal_img.url }}" class="rounded" alt=""></td>
                <td>{{ i.Status }}</td>
                <td>{{ i.Prize }}</td>
                <td>{{ i.Action }}

                    <a class="btn btn-secondary" href="{% url 'admin_panel:update_Register_Vehical' i.id %}" role="button">Update</a>
                    <a class="btn btn-danger" href="{% url 'admin_panel:delete_Register_Vehical' i.id %}" role="button">Delete</a>
                   
                </td>
            
            </tr>
            {% endfor %}
        </tbody>
    </table>

    
    
    {% endblock %}

templates/admin_panel/Rent_Rq_List_admin.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block head %}
    
<style>  
    
</style>

{% endblock %}

    {% block main %}
    


    
    <h1>Rent Rq Admin</h1>
    <br>
    <table class="table">
        <thead class="table-dark" style="border-radius: 25px;">
            <tr>
                <th scope="col">NO.</th>
                <th scope="col">UserId</th>
                <th scope="col">StartDate</th>
                <th scope="col">EndDate</th>
                <th scope="col">Pickup</th>
                <th scope="col">Drop</th>
                <th scope="col">Addhar img</th>
                <th scope="col">Status</th>               
                <th scope="col">Action</th>               
                
            </tr>
        </thead>
        <tbody>
            {% for i in data %}
            <tr class="shadow p-3 mb-5 bg-body rounded" >
                <td scope="row">{{ forloop.counter }}</td>
                <td>{{ i.UserId }}</td>
                <td>{{ i.StartDate }}</td>
                <td>{{ i.EndDate }}</td>
                <td>{{ i.Pickup }}</td>
                <td>{{ i.Drop }}</td>
                <td>
                    {% if i.Addhar_img %}
                    <img src="{{ i.Addhar_img.url }}" style="height: 75px;" class="rounded" alt="">
                    {% else %}
                    No Img
                    {% endif %}
                </td>
                <td>{{ i.Status }}</td>
                 
                <td>
                    {% if i.Status == "Pending" %}
                    <a class="btn btn-success" href="{% url 'admin_panel:accept_rent_req' i.id %}" role="button">Accept</a>
                    <a class="btn btn-danger" href="{% url 'admin_panel:reject_rent_req' i.id %}" role="button">Reject</a>
                    {% elif  i.Status == "Accepted" %}
                    <a class="btn btn-danger" href="{% url 'admin_panel:reject_rent_req' i.id %}" role="button">Reject</a>

                    {% else %}
                    <a class="btn btn-success" href="{% url 'admin_panel:accept_rent_req' i.id %}" role="button">Accept</a>

                    {% endif %}
                </td>        
                
            </tr>
            {% endfor %}
        </tbody>
    </table>

    
    
    {% endblock %}

templates/admin_panel/Vehical_Variant.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block head %}
    
<style>
    /* .table{
        background-color: rgb(33, 152, 199) !important;
        border-radius: 25px;
        
    } */
    
    
</style>

      {% endblock %}

    {% block main %}
    



    <a class="btn btn-danger" href="{% url 'admin_panel:Add_Vehical_Variant' %}">Add New Variant</a> <br/> <br> <br>

    {% for i in types %}
        <a href="{% url 'admin_panel:type_wise_category_in_variant' i.id %}" type="button" class="btn btn-outline-dark"> {{ i.Type_Name }} </a>
    {% endfor %}


    <h1>Vehical Variant </h1>
    <table class="table">
        <thead class="table-dark" >
            <tr>
                <th scope="col">NO.</th>
                <th scope="col">Variant Photo</th>
                <th scope="col">Variant_Name</th>
                <th scope="col">Vahical_Type</th>
                <th scope="col">Brand_n</th>
                <th scope="col">Vahical_catagory</th>
                <th scope="col">Fuel_Type</th>
                <th scope="col">Seat_Capacity</th>
                <th scope="col">Air_Condition</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for i in data %}
            <tr class="shadow p-3 mb-5 bg-body rounded" >
                <td  scope="row">{{ forloop.counter }}</td>
                <td ><img src="{{i.Variant_Photo.url}}" class="img" alt="">
                <td >{{ i.Variant_Name }}</td>
                <td >{{ i.Vahical_Type }}</td>
                <td >{{ i.Brand_n }}</td>
                <td >{{ i.Vahical_catagory }}</td>
                <td >{{ i.Fuel_Type }}</td>
                <td >{{ i.Seat_Capacity }}</td>
                <td >{{ i.Air_Condition }}</td>
                <td >{{ i.Action }}

                    <a class="btn btn-secondary" href="{% url 'admin_panel:updatevariant' i.id %}" role="button">Update</a>
                    <a class="btn btn-danger" href="{% url 'admin_panel:deletevariant' i.id %}" role="button">Delete</a>
                   
                </td>
            
            </tr>
            {% endfor %}
        </tbody>
    </table>

    
    
    {% endblock %}

templates/admin_panel/owner_Rq_List.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block head %}
    
<style>  
    
</style>

      {% endblock %}

    {% block main %}

    <br>
    <br>

    

    <h1>Owner Rq List</h1>
    <br>
    <table class="table">
        <thead class="table-dark" style="border-radius: 25px;">
            <tr>
                <th scope="col">NO.</th>
                <th scope="col">vehical_Variant</th>
                <th scope="col">Vehical_Number</th>
                <th scope="col">Model_Year</th>
                <th scope="col">KM_reading</th>
                <th scope="col">Vehical_Orignal_img</th>
                <th scope="col">Owner_Driving_Licence</th>
                <th scope="col">RCBOOK</th>
                <th scope="col">Prize Per Day</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for i in data %}
            <tr class="shadow p-3 mb-5 bg-body rounded" >
                <td scope="row">{{ forloop.counter }}</td>
                <!-- <td><img src="{{i.Variant_Photo.url}}" class="img" alt=""> -->
                <td>{{ i.vehical_Variant }}</td>
                <td>{{ i.Vehical_Number }}</td>
                <td>{{ i.Model_Year }}</td>
                <td>{{ i.KM_reading }}</td>
                <td>
                    {% if i.Vehical_Orignal_img %}
                    <img src="{{ i.Vehical_Orignal_img.url }}" class="rounded" alt="">
                    {% else %}
                    No Img
                    {% endif %}
                </td>
                <td>
                    {% if i.Owner_Driving_Licence %}
                    <img src="{{ i.Owner_Driving_Licence.url }}" class="rounded" alt="">
                    {% else %}
                    No Img
                    {% endif %}
                </td>
                <td>
                    {% if i.RCBOOK %}
                    <img src="{{ i.RCBOOK.url }}" class="rounded" alt="">
                    {% else %}
                    No Img
                    {% endif %}
                </td>
                <td>{{ i.Prize }}</td>
                <td>{{ i.Status }}</td>
                <td>
                    {% if i.Status == "Pending" %}
                    <a class="btn btn-success" href="{% url 'admin_panel:accept_owner_req' i.id %}" role="button">Accept</a>
                    <a class="btn btn-danger" href="{% url 'admin_panel:reject_owner_req' i.id %}" role="button">Reject</a>
                    {% elif  i.Status == "Accepted" %}
                    <a class="btn btn-danger" href="{% url 'admin_panel:reject_owner_req' i.id %}" role="button">Reject</a>

                    {% else %}
                    <a class="btn btn-success" href="{% url 'admin_panel:accept_owner_req' i.id %}" role="button">Accept</a>

                    {% endif %}
                </td>            
            </tr>
            {% endfor %}
        </tbody>
    </table>

    
    
    {% endblock %}

templates/admin_panel/vehical_brand.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block head %}
    
<style>
    /* .table{
        background-color: rgb(33, 152, 199) !important;
        border-radius: 25px;
        
    } */
    
    
</style>

      {% endblock %}

    {% block main %}
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        

        <button class="btn btn-danger" type="submit"> Submit</button>
    </form>

    

    <br>
    <br>

    <h1>Vehical Brand </h1>
    <table class="table">
        <thead class="table-dark">
            <tr>
                <th scope="col">NO.</th>
                <th scope="col">Brand Name</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for i in data %}
            <tr class="shadow p-3 mb-5 bg-body rounded" >
                <td scope="row">{{ forloop.counter }}</td>
                <td>{{ i.BrandName }}</td>
                <td>{{ i.Action }}
            
                
                    <a class="btn btn-secondary" href="{% url 'admin_panel:updatebrand' i.id %}" role="button">Update</a>
                    <a class="btn btn-danger" href="{% url 'admin_panel:deletebrand' i.id %}" role="button">Delete</a>
                   
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
    {% endblock %}

templates/admin_panel/vehical_category.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block head %}
    
<style>
    /* .table{
        background-color: rgb(33, 152, 199) !important;
        border-radius: 25px;
        
    } */
    
    
</style>

      {% endblock %}


    {% block main %}
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-danger" type="submit"> Submit</button>
    </form> 
    <br>
    <br>

    {% for i in types %}
    <a href="{% url 'admin_panel:type_wise_category' i.id %}" type="button" class="btn btn-outline-dark"> {{ i.Type_Name }} </a>
    {% endfor %}


    <h1>Vehical Category </h1>
    <table class="table">
        <thead class="table-dark" >
            <tr >
                <th scope="col">NO.</th>
                <th scope="col">Category Name</th>
                <th scope="col">Vehical Type</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for i in data %}
            <tr class="shadow p-3 mb-5 bg-body rounded" >
                <td scope="row">{{ forloop.counter }}</td>
                <td>{{ i.Category_Name }}</td>
                <td>{{ i.Vehical_TypeID }}</td>
                <td>{{ i.Action }}

                    <a class="btn btn-secondary" href="{% url 'admin_panel:updatecategory' i.id %}" role="button">Update</a>
                    <a class="btn btn-danger" href="{% url 'admin_panel:deletecategory' i.id %}" role="button">Delete</a>
                   
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
    {% endblock %}

templates/admin_panel/vehical_type.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block head %}
    
<style>
    /* .table{
        background-color: rgb(33, 152, 199) !important;
        border-radius: 25px;
        
    } */
    .img{
        /* width: 100%; */
        height: 60px;
        border-radius: 12px;
    }
    
    
</style>

      {% endblock %}


    {% block main %}
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-danger"> Submit</button>
    </form>

    <br>
    <br>

    <h1>Vehical Type </h1>
    <table class="table">
        <thead class="table-dark">
            <tr>
                <th scope="col">NO.</th>
                <th scope="col">Category Name </th>
                <th scope="col">Image</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for i in data %}
            <tr class="shadow p-3 mb-5 bg-body rounded" >
                <td scope="row">{{ forloop.counter }}</td>
                <td>{{ i.Type_Name }}</td>
                <td><img src="{{i.Type_Image.url}}" class="img" alt="">
                    <td>
                <a class="btn btn-secondary" href="{% url 'admin_panel:updatetype' i.id %}" role="button">Update</a>
                <a class="btn btn-danger" href="{% url 'admin_panel:deletetype' i.id %}" role="button">Delete</a>
                   
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    
   

    {% endblock %}